{% set version = "1.7.1" %}

package:
  name: ninja
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha1: 556ed5f8ee49753af1cf4b0ab2315d39d1954d58

build:
  number: 0
  msvc_compiler: 9.0  # [win]
  # NOTE: Ninja is agnostic to the Python version, so there is no point in
  # building it on every python version. On the other hand, Windows CI fails
  # to build Ninja using Python 3.5, so we stick to Python 2.7 for all
  # platforms to be consistent.
  skip: True
  skip: False  # [py27]

requirements:
  build:
    - python
  run:
    - vs2008_runtime  # [win]

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache License, Version 2.0
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
