{% set version = "1.9.0" %}
{% set archive_version = "28a7d1491367de7b39c854d166114f76d272f04f" %}

package:
  name: ninja
  version: {{ version }}

source:
  fn: {{ archive_version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/{{ archive_version }}.tar.gz
  sha256: ed625f642ea113299d42facacf90e3135b87d2f83c6ed1040b710b6afdbedc9d

build:
  number: 1
  skip: true  # [win and vc!=14]
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - python
  run:
    - vs2015_runtime  # [win]

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache 2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
