{% set version = "1.11.1" %}

package:
  name: ninja
  version: {{ version }}

source:
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha256: 31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea

build:
  number: 1

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - python *

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
    - xhochy
    - henryiii
