{% set version = "1.7.2" %}

package:
  name: ninja
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha1: a50e9008e90339d052f741e9c52a3475aa108fbb

build:
  number: 0
  msvc_compiler: 9.0  # [win]
  # NOTE: Ninja is agnostic to the Python version, so there is no point in
  # building it on every python version. On the other hand, Windows CI fails
  # to build Ninja using Python 3.5, so we stick to Python 2.7 for all
  # platforms to be consistent.
  skip: True  # [not py27]

requirements:
  build:
    - python
  run:
    - vs2008_runtime  # [win]

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache 2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
