{% set version = "1.12.1" %}

package:
  name: ninja
  version: {{ version }}

source:
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha256: 821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - python *

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
    - xhochy
    - henryiii
