{% set version = "1.9.0" %}
{% set archive_version = "1.9.0.g99df1.kitware.dyndep-1.jobserver-1" %}

package:
  name: ninja
  version: {{ version }}

# Kitware maintains this branch of Ninja in order to provide features
# that have not yet been integrated upstream:
#
# * Dynamic dependency discovery needed for Fortran builds
# * make-style jobserver support
#
# See https://github.com/Kitware/ninja
source:
  fn: v{{ archive_version }}.tar.gz
  url: https://github.com/kitware/ninja/archive/v{{ archive_version }}.tar.gz
  sha256: b7bc3d91e906b92d2e0887639e8ed6b0c45b28e339dda2dbb66c1388c86a9fcf

build:
  number: 1
  skip: true  # [win and vc!=14]
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - python
  run:
    - vs2015_runtime  # [win]

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache 2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
