travis:
  secure:
    BINSTAR_TOKEN: W81LqunOBpT/sQskS2FvKSyLlD43FO+4Yi52u7ohCviE5W6UmC72JffGplyyzIztiVMtdBLCLdn0OMzV+JZSV13B87zRDyB0v3COs4oTjO1mR3XWgU2X1+sggBeYe7hAeZZl5a8YfvDe4dqbF1vW4upB5sZ8/5hnvP0Dbhlphe9Q3g2kyl+tuXjZpXZcUe6239OBA9oajfPowz4je6MJMDi2RnetkCdZTcRrfGQy2Qa7sliUgGbL3M4OCRnQT1zAwwl1cIhJm9HTGdejyNgq1rgBFT787Y3P8O5Cg2ZaHbVUCWZ9dShXGUshgLXWzUrhR4RprxcVoftDWhdI9YvVni7wqWa4vuPNqqbW35N8e4BXCQC0MbOfpfYMBQjNSjBzJ5bWVErYDU+pCqGsDPgAGetLKL/oVpHHwnMrKZn6YUss4itUf0hHMtsbYMirB59cnr9erpq/fiVrDAymcyL5Bp21NKZcLclTPcNIH4FX7sjL6Jo0++2p38ysn+csR0ydXTX20p/20NvXV1MMjUYvdHE4LKXhzjjhPx7nTEW1EIg+uDSl4vyFO974/KokBf2LrEacSL25nChtMTKBTQoFc6b0xh2mKUJcOLNrawfLx9wbrkk5rlv1/ONP2nx84jJ4TinM4wA1YlfThmCpX9PrlL5YI3GVivH8pnUzdOXyaDw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
